### ISSUE TITLE
EventID 1644 (LDAP) no longer necessary

### ISSUE THREAD

**Issue by mb-northwave** [thalpius/Microsoft-Defender-for-Identity-Configuration-Checker#6]
In the latest documentation, Microsoft says EventID 1644 (with the 4 regkeys) is no longer needed.
Changelog: https://learn.microsoft.com/en-us/defender-for-identity/whats-new#defender-for-identity-release-2201
Documentation: https://learn.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection#event-id-1644

Please remove from checker. And add a note that if the regkeys are there, they should be removed :)

**Comment by thalpius** [comment]
Good point and thank you for bringing this to my attention. I've updated the code and added a new release as well.
